# Generated by Django 5.1.6 on 2025-02-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Name')),
                ('ico_code', models.CharField(max_length=128, unique=True, verbose_name='Ico Code')),
                ('icon', models.ImageField(upload_to='country/', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='MainConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_store_url', models.CharField(max_length=128, verbose_name='Application Store')),
                ('play_market_url', models.CharField(max_length=128, verbose_name='Play Market')),
            ],
            options={
                'verbose_name': 'Main configuration',
                'verbose_name_plural': 'Main configuration',
            },
        ),
    ]
